# Generated by Django 2.2.2 on 2019-06-13 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('o', 'Open'), ('c', 'Closed')], default='o', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('file', models.FileField(upload_to='videos/')),
                ('pin', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='videos/')),
                ('album', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='images.Album')),
            ],
        ),
        migrations.CreateModel(
            name='TFModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('videos', models.IntegerField(default=0, editable=False, max_length=5)),
                ('accuracy', models.CharField(default='100%', editable=False, max_length=4)),
                ('album', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='images.Album')),
            ],
        ),
    ]
