# Generated by Django 2.2.3 on 2019-07-19 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('o', 'Open'), ('c', 'Closed')], default='o', max_length=1)),
                ('model_status', models.CharField(choices=[('s', 'todo'), ('t', 'Training'), ('c', 'Created')], default='s', max_length=1)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=images.models.update_filename)),
                ('pin', models.CharField(max_length=6)),
                ('album', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Album')),
            ],
        ),
        migrations.CreateModel(
            name='TFModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('videos', models.IntegerField(default=0, editable=False, max_length=5)),
                ('album_model', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Album')),
            ],
        ),
    ]
