# Generated by Django 2.2.2 on 2019-06-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
