# Generated by Django 2.2.3 on 2019-07-03 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tfmodel',
            name='album_model',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Album'),
        ),
        migrations.AlterField(
            model_name='video',
            name='album_vdo',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Album'),
        ),
    ]
