# Generated by Django 2.2.2 on 2019-06-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('t', 'todo'), ('p', 'Processing'), ('c', 'Created')], default='t', max_length=1),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
