# Generated by Django 2.2.2 on 2019-06-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='pin',
            field=models.CharField(editable=False, max_length=6),
        ),
    ]
