# Generated by Django 2.2.2 on 2019-06-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190606_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='cover',
            new_name='file',
        ),
    ]
