# Generated by Django 2.2.2 on 2019-06-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20190606_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Video',
        ),
    ]
