# Generated by Django 2.2.2 on 2019-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20190611_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('o', 'Open'), ('c', 'Closed')], default='o', max_length=1),
        ),
    ]
