# Generated by Django 2.2.2 on 2019-06-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_album_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='status',
        ),
    ]
