# Generated by Django 2.2.2 on 2019-06-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20190607_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='images.Video')),
                ('category', models.CharField(choices=[('ART', 'art')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
