# Generated by Django 2.2.2 on 2019-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20190611_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='pin',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='videofile',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
